apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
spec:
  destination:
    namespace: argocd-notifications
    server: https://kubernetes.default.svc
  project: default
  source:
    path: notifications
    repoURL: https://github.com/mAlfosea/argoCD.git
    targetRevision: main
  syncPolicy:
    automated: {}
