apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-monitor
  namespace: argocd
spec:
  destination:
    namespace: service-monitor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: servicemonitor
    repoURL: https://github.com/mAlfosea/argoCD.git
    targetRevision: main
    kustomize:
      enableHelm: true
