apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemonitor
  namespace: argocd
spec:
  destination:
    namespace: monitorservice
    server: https://kubernetes.default.svc
  project: default
  source:
    path: servicemonitor
    repoURL: https://github.com/mAlfosea/argoCD.git
    targetRevision: main
