apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prometheus-installation
    repoURL: https://github.com/mAlfosea/argoCD.git
    targetRevision: main
