apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: prometheusoperator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prometheus-installation
    repoURL: https://github.com/mAlfosea/argoCD.git
    targetRevision: main
