apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus-operator
    version: 58.5.2
    repo: https://prometheus-community.github.io/helm-charts
    namespace: prometheus-operator
    valuesInline:
      grafana:
        enabled: true
        adminPassword: admin
      prometheus:
        prometheusSpec:
          serviceMonitorSelector: {}
          podMonitorSelector: {}